# Project: receptiveField
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o C:/Users/himstien/Documents/GitHub/iCubFiles/neuronsLIF/neuronsLIF.o $(RES)
LINKOBJ  = main.o C:/Users/himstien/Documents/GitHub/iCubFiles/neuronsLIF/neuronsLIF.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -L"C:/Users/himstien/Documents/GitHub/iCubAudioAttention/InterProcess_Communication/AudioStreamHandler/Release" -L"C:/Users/himstien/Documents/GitHub/iCubFiles/neuronsLIF" -L"C:/Users/himstien/Documents/GitHub/iCubFiles/receptiveFilter"  -lgmon -pg  
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Users/himstien/Documents/GitHub/iCubFiles/neuronsLIF"  -I"C:/Users/himstien/Documents/GitHub/iCubFiles"  -I"C:/Users/himstien/Documents/GitHub/iCubFiles/receptiveFilters" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"C:/Program Files (x86)/robotology/yarp-2.3.22/include"  -I"C:/Users/himstien/Documents/GitHub/iCubFiles/neuronsLIF"  -I"C:/Users/himstien/Documents/GitHub/iCubFiles"  -I"C:/Users/himstien/Documents/GitHub/iCubFiles/receptiveFilters" 
BIN  = receptiveField.exe
CXXFLAGS = $(CXXINCS)   -pg
CFLAGS = $(INCS)   -pg
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before receptiveField.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "receptiveField.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

C:/Users/himstien/Documents/GitHub/iCubFiles/neuronsLIF/neuronsLIF.o: C:/Users/himstien/Documents/GitHub/iCubFiles/neuronsLIF/neuronsLIF.cpp
	$(CPP) -c C:/Users/himstien/Documents/GitHub/iCubFiles/neuronsLIF/neuronsLIF.cpp -o C:/Users/himstien/Documents/GitHub/iCubFiles/neuronsLIF/neuronsLIF.o $(CXXFLAGS)
